---
# tasks files for helloworld

- hosts: all
  tasks:
    - name: upgrade all packages
      become: yes
      yum: name=* state=latest

    - name: Installing nodeand nps
      yum:
        enablerepo: epel
        state: installed
        name:
        - nodejs
        - npm

    - name: Copying the application file
      copy:
        src:/home/ec2-user/swdv660/helloworld.js
        dest: /home/ec2-user/helloworld.js
        owner: ec2-user
        group: ec2-user
        mode: 0644
      notify: restart helloworld

     - name: Copying the upstart file
       copy:
        src: /home/ec2-user/swdv660/helloworld.conf
        dest: /etc/init/helloworld.conf
        owner: root
        group: root
        mode: 0644

     - name: restart helloworld
       service: name=helloworld state=restarted
       become: yes    
